$ErrorActionPreference = 'Stop'

Uninstall-ChocolateyFont "Vazir.ttf"
Uninstall-ChocolateyFont "Vazir-Thin.ttf"
Uninstall-ChocolateyFont "Vazir-Medium.ttf"
Uninstall-ChocolateyFont "Vazir-Light.ttf"
Uninstall-ChocolateyFont "Vazir-Bold.ttf"
Uninstall-ChocolateyFont "Vazir-Black.ttf"
Uninstall-ChocolateyFont "Vazir-Thin-FD.ttf"
Uninstall-ChocolateyFont "Vazir-Medium-FD.ttf"
Uninstall-ChocolateyFont "Vazir-Light-FD.ttf"
Uninstall-ChocolateyFont "Vazir-FD.ttf"
Uninstall-ChocolateyFont "Vazir-Bold-FD.ttf"
Uninstall-ChocolateyFont "Vazir-Black-FD.ttf"
Uninstall-ChocolateyFont "Vazir-Thin-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Medium-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Light-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Bold-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Black-FD-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Thin-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Medium-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Light-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Bold-WOL.ttf"
Uninstall-ChocolateyFont "Vazir-Black-WOL.ttf"
