$ErrorActionPreference = 'Stop'

Uninstall-ChocolateyFont "$toolsDir\Vazir.ttf"
Uninstall-ChocolateyFont "$toolsDir\Vazir-Thin.ttf"
Uninstall-ChocolateyFont "$toolsDir\Vazir-Medium.ttf"
Uninstall-ChocolateyFont "$toolsDir\Vazir-Light.ttf"
Uninstall-ChocolateyFont "$toolsDir\Vazir-Bold.ttf"
Uninstall-ChocolateyFont "$toolsDir\Vazir-Black.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-Thin-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-Medium-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-Light-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-Bold-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits\Vazir-Black-FD.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-Thin-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-Medium-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-Light-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-Bold-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Farsi-Digits-Without-Latin\Vazir-Black-FD-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-Thin-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-Medium-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-Light-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-Bold-WOL.ttf"
Uninstall-ChocolateyFont "$toolsDir\Without-Latin\Vazir-Black-WOL.ttf"
